In [2]:
!pip install numpy
!pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
num_of_models = 5
num_of_metrics = 6

In [5]:
V = np.absolute( np.random.normal(0, 1, size=(num_of_models, num_of_metrics)) )


weights = np.random.uniform(0,1,num_of_metrics)
weights = weights/weights.sum()
weights

array([0.09896565, 0.13649193, 0.27948986, 0.07386823, 0.1961126 ,
       0.21507173])



> **Дистрибутивний метод**



In [6]:
r_koefs_denom =  np.sum(V, axis=0)
r_koefs_denom_mat = np.repeat(r_koefs_denom, num_of_models).reshape(num_of_metrics, num_of_models)
r_koefs_denom_mat = np.transpose(r_koefs_denom_mat)

r_koef_mat = np.divide(V, r_koefs_denom_mat)

weights_mat = np.repeat(weights, num_of_models).reshape(num_of_models, num_of_metrics)

distributed_rating_mat = np.multiply(weights_mat, r_koef_mat)

distributed_rating = distributed_rating_mat.sum(axis=1)
distributed_rating

array([0.12617695, 0.26994648, 0.2796839 , 0.1240009 , 0.22986293])

In [7]:
r_koefs_denom =  np.max(V, axis=0)
r_koefs_denom_mat = np.repeat(r_koefs_denom, num_of_models).reshape(num_of_metrics, num_of_models)
r_koefs_denom_mat = np.transpose(r_koefs_denom_mat)

r_koef_mat = np.divide(V, r_koefs_denom_mat)

weights_mat = np.repeat(weights, num_of_models).reshape(num_of_models, num_of_metrics)

distributed_rating_mat = np.multiply(weights_mat, r_koef_mat)

modified_distributed_rating = distributed_rating_mat.sum(axis=1)
modified_distributed_rating

array([0.33880523, 0.69951161, 0.68257724, 0.33678782, 0.59703601])

In [8]:
weights_mat = np.repeat(weights, num_of_models).reshape(num_of_models, num_of_metrics)

power_mat = np.power(V, weights_mat)

power_rating = power_mat.prod(axis=1)
power_rating

array([0.8097172 , 1.11770421, 0.66367224, 0.51872751, 0.64423829])

In [9]:
weights_mat = np.repeat(weights, num_of_models).reshape(num_of_models, num_of_metrics)
minimum_rating_mat = np.multiply(V, weights_mat)
minimum_rating = minimum_rating_mat.min(axis=1)
minimum_rating

array([0.04061234, 0.05319235, 0.019079  , 0.00309706, 0.0395174 ])

In [17]:
weights_agg = np.array([distributed_rating, modified_distributed_rating, power_rating, minimum_rating])
distributed_rating = distributed_rating/np.sum(distributed_rating)
modified_distributed_rating = modified_distributed_rating/np.sum(modified_distributed_rating)
power_rating = power_rating/np.sum(power_rating)
minimum_rating = minimum_rating/np.sum(minimum_rating)
print("distributed_rating: ")
print(distributed_rating)
print("modified_distributed_rating: ")
print(modified_distributed_rating)
print("power_rating: ")
print(power_rating)
print("minimum_rating: ")
print(minimum_rating)

distributed_rating: 
[0.12254101 0.26216766 0.27162449 0.12042767 0.22323917]
modified_distributed_rating: 
[0.12762382 0.26349753 0.25711856 0.12686388 0.22489622]
power_rating: 
[0.2156911  0.29773215 0.17678789 0.13817776 0.17161111]
minimum_rating: 
[0.2611757  0.34207705 0.122696   0.01991704 0.25413421]
